### ISSUE TITLE
Improve UI closing behavior

### ISSUE THREAD

**Issue by TQxTim** [clivebeckett/grav-plugin-admin-addon-media-metadata#14] opened 2020-07-16 14:05 UTC
Current behavior for  Admin Addon Media Metadata v1.1.0 with Admin Panel  v1.10.0-rc.14

When a user releases the mouse button outside the 'Edit metadata for media file' modal, it closes itself automatically and the added content is gone.
This happens for example, if someone marks the content of a text field for copy-paste and releases the button outside the modal.

One possible solution would be, if the modal only closes on mousedown instead mouseup events outside the modal.

**Comment by clivebeckett** [comment] 2020-07-18 07:51
Hi Tim,

thanks for your note. For the modal I just used a Grav core functionality – or at least I think so :) Can you try other modals and check whether it’s the same issue there? If I am right, I guess the [Grav Admin Plugin](https://github.com/getgrav/grav-plugin-admin/) should be the right place to post an issue like that.

Please let me know if you were able to find out more.

Cheers,
Clive.

**Comment by bitstarr** [comment] 2024-01-16 21:37
I could not reproduce the behaviour of marking and releasing outside the modal to close it. Seem like the admin native modal has improved and there was no further feedback here anyway.

**Closed by bitstarr** 2024-01-16 21:37 UTC
