### ISSUE TITLE
Not possible to create or change metadata of image with Grav v1.7.0-rc.20 - Admin v1.10.0-rc.20

### ISSUE THREAD

**Issue by tonhaarmans** [clivebeckett/grav-plugin-admin-addon-media-metadata#15] opened 2021-01-08 18:51 UTC
Hello, it takes ages and finally does not save a meta.yaml file with the plugin in Grav v1.7.0-rc.20 with Admin v1.10.0-rc.20.
See [screenshot](https://www.wideopenwindows.be/Screenshot-writing-metadata.jpg). Please tell me what to do. My client can only work from the admin section...

**Comment by clivebeckett** [comment] 2021-01-09 15:00
Hi @tonhaarmans 

thank you for your note. Unfortunately, without knowing more, I can’t really figure out what the problem is. I am using the plugin (v1.1.0) in exactly these Grav/Admin-Plugin versions and it works just fine.

**Comment by bitstarr** [comment] 2024-01-16 21:48
it's been long time and since there was no further information to reproduce the issue, I close this now.

**Closed by bitstarr** 2024-01-16 21:48 UTC
